RDR3ProvisionItemToDollars = {
    -- ['']
    [`PROVISION_SKINNED_CARCASS_DEER_HIGH_QUALITY`] = 00.10,
    [`PROVISION_SKINNED_CARCASS_DEER_PERFECT`] = 00.10,
    [`PROVISION_SKINNED_CARCASS_DEER_POOR`] = 00.10,

    [`PROVISION_ANIMAL_CARCASS_DEER_PERFECT`] = 00.10,
    [`PROVISION_ANIMAL_CARCASS_DEER_HIGH_QUALITY`] = 00.10,
    [`PROVISION_ANIMAL_CARCASS_DEER_POOR`] = 00.10,

    [`PROVISION_DEER_HIDE_POOR`]     = 00.10,
    [`PROVISION_DEER_HIDE_PRISTINE`] = 00.20,
    [`PROVISION_DEER_HIDE`]          = 00.30,

    [`PROVISION_COUGAR_FUR`]            = 00.10,
    
    [`PROVISION_PRONGHORN_FUR`]         = 00.10,
    
    [`PROVISION_BEAVER_FUR_PRISTINE`]   = 00.10,
    
    [`PROVISION_COYOTE_FUR`]            = 00.10,
    
    [`PROVISION_BOAR_SKIN_POOR`]        = 00.10,
    
    [`PROVISION_SHEEP_WOOL_PRISTINE`]   = 00.10,
    
    [`PROVISION_PANTHER_FUR_POOR`]      = 00.10,
    
    [`PROVISION_BUCK_FUR`]                    = 00.20,
    [`PROVISION_BUCK_FUR_POOR`]               = 00.20,
    [`PROVISION_BUCK_FUR_PRISTINE`]           = 00.40,
    [`PROVISION_BUCK_LEGENDARY_FUR_PRISTINE`] = 00.60,
    
    [`PROVISION_GOAT_HAIR`]             = 00.10,
    [`PROVISION_GOAT_HAIR_POOR`]        = 00.10,

    [`PROVISION_FOX_FUR`]               = 00.10,
    [`PROVISION_FOX_FUR_POOR`]          = 00.10,
    [`PROVISION_FOX_FUR_PRISTINE`]      = 00.10,

    [`PROVISION_WOLF_FUR`]              = 00.10,
    [`PROVISION_WOLF_FUR_POOR`]         = 00.10,
    [`PROVISION_WOLF_FUR_PRISTINE`]     = 00.10,

    [`PROVISION_WOLF_LEGENDARY_FUR_01`] = 00.10,
    [`PROVISION_WOLF_LEGENDARY_FUR_02`] = 00.10,
    [`PROVISION_WOLF_LEGENDARY_FUR_03`] = 00.10,

    [`PROVISION_ARMADILLO_SKIN_POOR`] = 00.10,
    [`PROVISION_ARMADILLO_SKIN_PRISTINE`] = 00.10,
    [`PROVISION_ARMADILLO_SKIN`] = 00.10,

    [`PROVISION_BADGER_CLAW`] = 00.10,
    [`PROVISION_BADGER_PELT_POOR`] = 00.10,
    [`PROVISION_BADGER_PELT_PRISTINE`] = 00.10,
    [`PROVISION_BADGER_PELT`] = 00.10,

    [`PROVISION_BEAR_CLAW`] = 00.10,
    [`PROVISION_BEAR_FUR_POOR`] = 00.10,
    [`PROVISION_BEAR_FUR_PRISTINE`] = 00.10,
    [`PROVISION_BEAR_FUR`] = 00.10,
    [`PROVISION_BEAR_LEGENDARY_CLAW`] = 00.10,
    [`PROVISION_BEAR_LEGENDARY_FUR_PRISTINE`] = 00.10,

    [`PROVISION_BEAVER_FUR_POOR`] = 00.10,
    [`PROVISION_BEAVER_FUR_PRISTINE`] = 00.10,
    [`PROVISION_BEAVER_FUR`] = 00.10,
    [`PROVISION_BEAVER_LEGENDARY_FUR_PRISTINE`] = 00.10,
    [`PROVISION_BEAVER_TOOTH_LEGENDARY`] = 00.10,

    [`PROVISION_BLACK_BEAR_FUR_POOR`]     = 00.10,
    [`PROVISION_BLACK_BEAR_FUR_PRISTINE`] = 00.10,
    [`PROVISION_BLACK_BEAR_FUR`]          = 00.10,

    [`PROVISION_FISH_BLUEGILL_LEGENDARY`] = 00.10,
    [`PROVISION_FISH_BLUEGILL_POOR`]      = 00.10,
    [`PROVISION_FISH_BLUEGILL`]           = 00.10,

    [`PROVISION_FISH_BULLHEAD_CATFISH_LEGENDARY`] = 00.10,
    [`PROVISION_FISH_BULLHEAD_CATFISH_POOR`]      = 00.10,
    [`PROVISION_FISH_BULLHEAD_CATFISH`]           = 00.10,

    [`PROVISION_FISH_CHAIN_PICKEREL_LEGENDARY`] = 00.10,
    [`PROVISION_FISH_CHAIN_PICKEREL_POOR`]      = 00.10,
    [`PROVISION_FISH_CHAIN_PICKEREL`]           = 00.10,

    [`PROVISION_FISH_CHANNEL_CATFISH_LEGENDARY`] = 00.10,
    [`PROVISION_FISH_CHANNEL_CATFISH_POOR`]      = 00.10,
    [`PROVISION_FISH_CHANNEL_CATFISH`]           = 00.10,

    [`PROVISION_FISH_LAKE_STURGEON_LEGENDARY`] = 00.10,
    [`PROVISION_FISH_LAKE_STURGEON_POOR`]      = 00.10,
    [`PROVISION_FISH_LAKE_STURGEON`]           = 00.10,

    [`PROVISION_FISH_LARGEMOUTH_BASS_LEGENDARY`] = 00.10,
    [`PROVISION_FISH_LARGEMOUTH_BASS_POOR`]      = 00.10,
    [`PROVISION_FISH_LARGEMOUTH_BASS`]           = 00.10,

    [`PROVISION_FISH_LONGNOSE_GAR_LEGENDARY`] = 00.10,
    [`PROVISION_FISH_LONGNOSE_GAR_POOR`]      = 00.10,
    [`PROVISION_FISH_LONGNOSE_GAR`]           = 00.10,

    [`PROVISION_FISH_MUSKIE_LEGENDARY`] = 00.10,
    [`PROVISION_FISH_MUSKIE_POOR`]      = 00.10,
    [`PROVISION_FISH_MUSKIE`]           = 00.10,

    [`PROVISION_FISH_NORTHERN_PIKE_LEGENDARY`] = 00.10,
    [`PROVISION_FISH_NORTHERN_PIKE_POOR`]      = 00.10,
    [`PROVISION_FISH_NORTHERN_PIKE`]           = 00.10,

    [`PROVISION_FISH_PERCH_LEGENDARY`] = 00.10,
    [`PROVISION_FISH_PERCH_POOR`]      = 00.10,
    [`PROVISION_FISH_PERCH`]           = 00.10,

    [`PROVISION_FISH_REDFIN_PICKEREL_LEGENDARY`] = 00.10,
    [`PROVISION_FISH_REDFIN_PICKEREL_POOR`]      = 00.10,
    [`PROVISION_FISH_REDFIN_PICKEREL`]           = 00.10,

    [`PROVISION_FISH_ROCK_BASS_LEGENDARY`] = 00.10,
    [`PROVISION_FISH_ROCK_BASS_POOR`]      = 00.10,
    [`PROVISION_FISH_ROCK_BASS`]           = 00.10,

    [`PROVISION_FISH_SMALLMOUTH_BASS_LEGENDARY`] = 00.10,
    [`PROVISION_FISH_SMALLMOUTH_BASS_POOR`]      = 00.10,
    [`PROVISION_FISH_SMALLMOUTH_BASS`]           = 00.10,

    [`PROVISION_FISH_SOCKEYE_SALMON_LEGENDARY`] = 00.10,
    [`PROVISION_FISH_SOCKEYE_SALMON_POOR`]      = 00.10,
    [`PROVISION_FISH_SOCKEYE_SALMON`]           = 00.10,

    [`PROVISION_FISH_STEELHEAD_TROUT_LEGENDARY`] = 00.10,
    [`PROVISION_FISH_STEELHEAD_TROUT_POOR`]      = 00.10,
    [`PROVISION_FISH_STEELHEAD_TROUT`]           = 00.10,

    [`PROVISION_FLAKEY_FISH_MEAT`] = 00.10,

    [`PROVISION_FOX_CLAW_LEGENDARY`]         = 00.10,
    [`PROVISION_FOX_FUR_POOR`]               = 00.10,
    [`PROVISION_FOX_FUR_PRISTINE`]           = 00.10,
    [`PROVISION_FOX_FUR`]                    = 00.10,
    [`PROVISION_FOX_LEGENDARY_FUR_PRISTINE`] = 00.10,

    [`PROVISION_GAME_MEAT`] = 00.10,

    [`PROVISION_GAMEY_BIRD_MEAT`] = 00.10,

    [`PROVISION_GILA_SKIN_POOR`] = 00.10,
    [`PROVISION_GILA_SKIN_PRISTINE`] = 00.10,
    [`PROVISION_GILA_SKIN`] = 00.10,

    [`PROVISION_GOAT_HAIR_POOR`] = 00.10,
    [`PROVISION_GOAT_HAIR_PRISTINE`] = 00.10,
    [`PROVISION_GOAT_HAIR`] = 00.10,

    [`PROVISION_GOOSE_FEATHER`] = 00.10,

    [`PROVISION_GRISTLY_MUTTON`] = 00.10,

    [`PROVISION_GRITTY_FISH_MEAT`] = 00.10,

    [`PROVISION_HAWK_FEATHER`] = 00.10,

    [`PROVISION_HERON_FEATHER`] = 00.10,

    [`PROVISION_HERPTILE_MEAT`] = 00.10,

    [`PROVISION_IGUANA_SKIN_POOR`]     = 00.10,
    [`PROVISION_IGUANA_SKIN_PRISTINE`] = 00.10,
    [`PROVISION_IGUANA_SKIN`]          = 00.10,

    [`PROVISION_JAVELINA_SKIN_POOR`]     = 00.10,
    [`PROVISION_JAVELINA_SKIN_PRISTINE`] = 00.10,
    [`PROVISION_JAVELINA_SKIN`]          = 00.10,

    [`PROVISION_LIONS_PAW`] = 00.10,

    [`PROVISION_LOANSHARK_SKINS`] = 00.10,

    [`PROVISION_LOON_FEATHER`] = 00.10,

    [`PROVISION_MATURE_VENISON`] = 00.10,
    
    [`PROVISION_MOOSE_ANTLER_LEGENDARY`]       = 00.10,
    [`PROVISION_MOOSE_ANTLER`]                 = 00.10,
    [`PROVISION_MOOSE_FUR_POOR`]               = 00.10,
    [`PROVISION_MOOSE_FUR_PRISTINE`]           = 00.10,
    [`PROVISION_MOOSE_FUR`]                    = 00.10,
    [`PROVISION_MOOSE_LEGENDARY_FUR_PRISTINE`] = 00.10,

    [`PROVISION_MUSKRAT_FUR_POOR`]     = 00.10,
    [`PROVISION_MUSKRAT_FUR_PRISTINE`] = 00.10,
    [`PROVISION_MUSKRAT_FUR`]          = 00.10,

    [`PROVISION_OPOSSUM_FUR_POOR`]     = 00.10,
    [`PROVISION_OPOSSUM_FUR_PRISTINE`] = 00.10,
    [`PROVISION_OPOSSUM_FUR`]          = 00.10,

    [`PROVISION_ORIOLE_FEATHER`] = 00.10,

    [`PROVISION_OWL_FEATHER`] = 00.10,

    [`PROVISION_OXEN_HIDE_POOR`]     = 00.10,
    [`PROVISION_OXEN_HIDE_PRISTINE`] = 00.10,
    [`PROVISION_OXEN_HIDE`]          = 00.10,
    [`PROVISION_OXEN_HORN`]          = 00.10,
    
    [`PROVISION_PANTHER_EYE_LEGENDARY`]          = 00.10,
    [`PROVISION_PANTHER_FUR_POOR`]               = 00.10,
    [`PROVISION_PANTHER_FUR_PRISTINE`]           = 00.10,
    [`PROVISION_PANTHER_FUR`]                    = 00.10,
    [`PROVISION_PANTHER_LEGENDARY_FUR_PRISTINE`] = 00.10,

    [`PROVISION_PARAKEET_FEATHER`] = 00.10,

    [`PROVISION_PARROT_FEATHER`] = 00.10,

    [`PROVISION_PELICAN_FEATHER`] = 00.10,

    [`PROVISION_PHEASANT_FEATHER`] = 00.10,

    [`PROVISION_PIG_SKIN_POOR`]     = 00.10,
    [`PROVISION_PIG_SKIN_PRISTINE`] = 00.10,
    [`PROVISION_PIG_SKIN`]          = 00.10,
}